# Generated by Django 2.1.4 on 2018-12-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSSFeedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(blank=True, max_length=5, null=True)),
                ('date', models.DateTimeField(blank=True, default=None, null=True)),
                ('link', models.URLField(blank=True, default=None, null=True)),
                ('exchange_rate', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('summary', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rssfeedmodel',
            unique_together={('target', 'date')},
        ),
    ]
